// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AllQuestionsByStateResponse struct {
	Base
	Data map[string][]QuestionItem `json:"data"`
}

type AppConfigData struct {
	TotalQuestions int                `json:"totalQuestions"`
	ExamQuestions  int                `json:"examQuestions"`
	ExamMinutes    int                `json:"examMinutes"`
	PassScore      int                `json:"passScore"`
	LanguageModes  []LanguageModeItem `json:"languageModes"`
}

type AuthResponse struct {
	Base
	Data struct {
		User
		Jwt
	} `json:"data"`
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteInviteCodeRequest struct {
	ID string `path:"id" json:"id"`
}

type DeleteInviteCodeResponse struct {
	Base
}

type DeleteUserRequest struct {
	ID string `path:"id" json:"id"`
}

type DeleteUserResponse struct {
	Base
}

type EnableInviteCodeRequest struct {
	ID        string `path:"id" json:"id"`
	IsEnabled bool   `json:"is_enabled"`
}

type EnableInviteCodeResponse struct {
	Base
}

type EnableUserRequest struct {
	ID        string `path:"id" json:"id"`
	IsEnabled bool   `json:"is_enabled"`
}

type EnableUserResponse struct {
	Base
}

type Filter struct {
	PageNo   int `form:"pageNo,optional,default=1" json:"pageNo" validate:"omitempty,gte=1"`
	PageSize int `form:"pageSize,optional,default=10" json:"pageSize" validate:"omitempty,gte=1,lte=100"`
}

type GenerateInviteCodeRequest struct {
	Count int `json:"count,optional,default=1"` // 生成邀请码数量
}

type GenerateInviteCodeResponse struct {
	Base
	Data struct {
		Items []InviteCode `path:"items" json:"items"`
	} `json:"data"`
}

type GetConfigResponse struct {
	Base
	Data AppConfigData `json:"data"`
}

type GetExamQuestionsRequest struct {
	StateId string `form:"state_id,optional" json:"state_id,optional"`
}

type GetInviteCodeRequest struct {
	ID string `path:"id" json:"id"`
}

type GetInviteCodeResponse struct {
	Base
	Data struct {
		InviteCode
	} `json:"data"`
}

type GetQuestionRequest struct {
	QuestionId string `path:"question_id"`
}

type GetQuestionResponse struct {
	Base
	Data QuestionItem `json:"data"`
}

type GetUserRequest struct {
	ID string `path:"id"`
}

type GetUserResponse struct {
	Base
	Data struct {
		User
	} `json:"data"`
}

type InviteCode struct {
	Id        string `path:"id" json:"id"`
	Code      string `path:"code" json:"code"`
	UsedBy    string `path:"usedBy" json:"usedBy,omitempty"`
	ExpiresAt int64  `path:"expiresAt" json:"expiresAt"`
	CreatedBy string `path:"createdBy" json:"createdBy,omitempty"`
	IsEnabled bool   `path:"isEnabled" json:"is_enabled"`
	CreatedAt int64  `path:"createdAt" json:"createdAt"`
}

type Jwt struct {
	JwtToken   string `json:"jwt_token"`
	Expires    int64  `json:"expires"`
	MaxRefresh int64  `json:"max_refresh"`
}

type JwtRefreshResponse struct {
	AuthResponse
}

type LanguageModeItem struct {
	Value string `json:"value"`
	Label string `json:"label"`
}

type ListInviteCodeRequest struct {
	Filter
	AvailableOnly bool `form:"availableOnly,optional"` // 仅查看可用的邀请码（未使用、未过期、已启用）
}

type ListInviteCodeResponse struct {
	Base
	Data struct {
		Filter
		Total int64        `json:"total"`
		Items []InviteCode `path:"items" json:"items"`
	} `json:"data"`
}

type ListQuestionsResponse struct {
	Base
	Data struct {
		Total int64          `json:"total"`
		Items []QuestionItem `json:"items"`
	} `json:"data"`
}

type ListResponse struct {
	Data []interface{} `path:"data" json:"data"`
	Filter
	Total int64 `path:"total" json:"total"`
}

type ListStatesResponse struct {
	Base
	Data struct {
		Total int64       `json:"total"`
		Items []StateItem `json:"items"`
	} `json:"data"`
}

type ListUserRequest struct {
	Filter
}

type ListUserResponse struct {
	Base
	Data struct {
		Filter
		Total int64  `json:"total"`
		Items []User `path:"items" json:"items"`
	} `json:"data"`
}

type LoginRequest struct {
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AuthResponse
}

type LogoutResponse struct {
	Base
}

type QuestionItem struct {
	Id            string   `json:"id"`
	QuestionDe    string   `json:"questionDe"`
	QuestionCn    string   `json:"questionCn"`
	OptionsDe     []string `json:"optionsDe"`
	OptionsCn     []string `json:"optionsCn"`
	CorrectAnswer int      `json:"correctAnswer"`
	Explanation   string   `json:"explanation"`
	HasImage      bool     `json:"hasImage"`
	State         string   `json:"state"`
}

type RegisterRequest struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	InviteCode string `json:"invite_code"`
	Username   string `json:"username,optional"`
	Nickname   string `json:"nickname,optional"`
	Phone      string `json:"phone,optional"`
}

type RegisterResponse struct {
	AuthResponse
}

type Response struct {
	Base
	Data interface{} `path:"data" json:"data"`
}

type StateItem struct {
	Id     string `json:"id"`
	Slug   string `json:"slug"`
	Name   string `json:"name"`
	NameCn string `json:"nameCn"`
}

type StateQuestionsRequest struct {
	StateId string `path:"state_id"`
}

type UpdateUserRequest struct {
	Nickname    string `json:"nickname,optional" validate:"omitempty,max=50"`
	Description string `json:"description,optional" validate:"omitempty,max=500"`
}

type UpdateUserResponse struct {
	Base
	Data struct {
		User
	} `json:"data"`
}

type User struct {
	ID          string `path:"id" json:"id,omitempty"`
	Username    string `path:"username" json:"username,omitempty" validate:"omitempty,alphanum,min=6,max=50"`
	Email       string `path:"email" json:"email,omitempty" validate:"omitempty,email"`
	Password    string `path:"password" json:"password,omitempty"` // 仅登录/注册使用
	Phone       string `path:"phone" json:"phone,omitempty" validate:"omitempty,len=11,numeric"`
	Role        string `path:"role" json:"role,omitempty" validate:"omitempty,oneof=user admin guest"`
	Nickname    string `path:"nickname" json:"nickname,omitempty" validate:"omitempty,max=50"`
	IsEnabled   bool   `path:"isEnabled" json:"is_enabled,omitempty"`
	Description string `path:"description" json:"description,omitempty" validate:"omitempty,max=500"`
	InviteCode  string `path:"inviteCode" json:"invite_code,omitempty" validate:"omitempty,alphanum,min=4,max=32"`
	CreatedAt   int64  `path:"createdAt" json:"createdAt,omitempty"`
	UpdatedAt   int64  `path:"updatedAt" json:"updatedAt,omitempty"`
}
