// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId    int64  `json:"user_id"`
	Token     string `json:"token"`
	ExpiresIn int64  `json:"expires_in, default=3600"`
}

type LogoutResponse struct {
	Message string `json:"message"`
}

type RegisterRequest struct {
	Username string `json:"username, min=3, max=20"`
	Email    string `json:"email"`
	Password string `json:"password, min=8"`
}

type RegisterResponse struct {
	UserId  int64  `json:"user_id"`
	Token   string `json:"token"`
	Message string `json:"message"`
}
