// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	auth "deutsch/internal/handler/auth"
	config "deutsch/internal/handler/config"
	invitecode "deutsch/internal/handler/invitecode"
	progress "deutsch/internal/handler/progress"
	question "deutsch/internal/handler/question"
	user "deutsch/internal/handler/user"
	"deutsch/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/jwt/refresh",
				Handler: auth.JwtRefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/api/v1/auth"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/config",
				Handler: config.ConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/states",
				Handler: config.StatesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/validate/:id",
				Handler: invitecode.ValidateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/api/v1/invitecode"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: invitecode.GetInviteCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: invitecode.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/:id/enable",
					Handler: invitecode.EnableHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/generate",
					Handler: invitecode.GenerateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: invitecode.ListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/api/v1/invitecode"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/exams",
					Handler: progress.ListExamRecordsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/exams",
					Handler: progress.SubmitExamHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/exams/:id",
					Handler: progress.GetExamRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/learning",
					Handler: progress.GetLearningProgressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/learning",
					Handler: progress.RecordPracticeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/preferences",
					Handler: progress.GetPreferencesHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/preferences",
					Handler: progress.UpdatePreferencesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/wrong-questions",
					Handler: progress.ListWrongQuestionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/wrong-questions",
					Handler: progress.AddWrongQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/wrong-questions/:question_id",
					Handler: progress.RemoveWrongQuestionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/api/v1/progress"),
		rest.WithTimeout(5000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:question_id",
				Handler: question.GetQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/all",
				Handler: question.AllQuestionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/exam",
				Handler: question.ExamQuestionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/general",
				Handler: question.GeneralQuestionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/state/:state_id",
				Handler: question.StateQuestionsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/questions"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/profile",
					Handler: user.UpdateUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/:id/enable",
					Handler: user.EnableUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: user.ListUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
		rest.WithTimeout(3000*time.Millisecond),
	)
}
